version: "3.7"
services:
  mern-app-backend:
    image: node:16-alpine
    command: sh -c "npm install && npm run build && npx prisma generate && npm run dev"
    ports:
      - 4000:4000
    working_dir: /mern-app-backend
    environment:
      REDIS_HOST: redis://redis:6379
    volumes:
      - ./:/mern-app-backend

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  redis-data: